version: '3'
services:
    web: 
        build: ./proyecto
        restart: always
        command: "nodemon server/server"
        depends_on:
            - db
        ports: 
            - 8000:8000
        volumes:
            - ./proyecto:/opt/app
            - node_modules:/opt/app/node_modules
    db:
        image: mongo
        ports:
            - 27018:27017
        volumes:
            - $PWD/mongodata:/data/db
        restart: always

volumes:
   node_modules:
